#!/bin/sh
### BEGIN INIT INFO
# Provides:          sendsigs
# Required-Start:    
# Required-Stop:     
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Kill all remaining processes.
# Description: 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Kill all processes.
killall5 -15
killall5 -9

: exit 0
